spring:
  datasource:
    url: jdbc:mysql://47.105.217.81:3306/hz-iot
    username: root
    password: 7a23e9919540fce3
    hikari:
      keepalive-time: 60000
      connection-test-query: select 1

mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl


iot:
  tools:
    network-debugger:
      ip: hze2.com
