server:
  port: 12008
spring:
  threads:
    virtual:
      enabled: true
  main:
    banner-mode: off
  profiles:
    active: prod
mybatis-flex:
  global-config:
    print-banner: false

springdoc:
  group-configs:
    - group: "system-module"
      paths-to-match:
        - "/system/**"
    - group: "device-module"
      paths-to-match:
        - "/device-manager/**"
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
