@startuml
'https://plantuml.com/object-diagram

class ProductCategory{
    id
    name
    parentId
    sort
    remark
}
class Product{
    id
    name
    categoryId
    type
    configuration
    remark
}
class Device {
    id
    name
    productId
    configuration
    remark
}
class ThingModel{
    id
}

Product --> ProductCategory
@enduml
